### ISSUE TITLE
Wrong agent version?

### ISSUE THREAD

**Issue by cpoczatek** [DSPN/amazon-cloudformation-dse#24]
OpsCenter shows vvvv.

```Package-installed agent has the wrong version.
Click Upgrade Agents to install the correct version of the agent on all nodes.
```

Pretty sure this is due to bumping OpsC to 6.0.5 and not the DSE version...

**Comment by benofben** [comment]
Yeah.  Those need to match.

---------------------------------------------------
Ben Lackey
ben.lackey@outlook.com<mailto:ben.lackey@outlook.com>
+1 720 933 9852

On Dec 8, 2016, at 11:49 AM, Collin Poczatek <notifications@github.com<mailto:notifications@github.com>> wrote:


OpsCenter shows vvvv.

Click Upgrade Agents to install the correct version of the agent on all nodes.```

Pretty sure this is due to bumping OpsC to 6.0.5 and not the DSE version...


-

**Comment by cpoczatek** [comment]
Fixed in aws-testing branch of install-datastax-ubuntu. Note to future self: opsc version defined in:
- opscenter/install.sh : apt-get -y install opscenter=6.0.5
- dse/install.sh : opscenter_version=6.0.5
