### ISSUE TITLE
`readlink` should be `stat` on macOS

### ISSUE THREAD

**Issue by MadDataScience** [DSPN/amazon-cloudformation-dse#29]
When I tried running the deploy scripts on my Mac (OS 10.12) I got `readlink: illegal option -- f`. From what I could tell from the man file, it looks like macOS prefers `stat`, so I tried replacing instances of `readlink` with `stat` everywhere and it seems to be working. I don't know if `stat` would work just a well in other *NIX systems or if there should be something in the README showing how to adjust for that (or better yet, to detect which version to use in the script itself, though I could see that being annoyingly complicated for an edge case like this).

**Comment by MadDataScience** [comment]
Update: I realized that I should not replace readlink with stat _everywhere_ since some of it is meant to be run on an EC2 instance. From what I could the occurrence in `cfn-opscenter.json` (under `setup_cluster`) should be left alone.

#30 is still an issue even after I reverted cfn-opscenter.json back to the way it was, but I think I'm closer.

**Comment by cpoczatek** [comment]
Just pushed a fix for this, the 2 *deploy* scripts use readlink on linux and something else on macOS. 

It's a little hard for me to test on mac, could you let me know if it works?

The only stuff that gets executed locally are the 2 *deploy* shell scripts, everything else happens in ec2. All those calls to readlink are trying to do is get the absolute path of the template .json file to pass the aws cli a real url.

**Comment by cpoczatek** [comment]
Forgot to mention I also added an instance type variable to the top of *deploy-datacenter-lcm.sh* default *t2.medium*.

**Comment by cpoczatek** [comment]
I was able to test this on mac OS. Closing.
