### ISSUE TITLE
Unable to connect to cluster

### ISSUE THREAD

**Issue by MadDataScience** [DSPN/amazon-cloudformation-dse#30]
I'm not sure if this is related to #27 but after deploying both the opscenter and a datacenter (after changing `readlink` to `stat` as per #29 because I have a Mac) and both come up as "CREATE_COMPLETE", the Lifecycle Manager loads but when I go to the OpsCenter it asks if I want to create a new cluster or manage an existing one. I select the latter and enter one IP in the cluster (say, '172.31.30.71') and leave the rest as default and get the following error: 

> OpsCenter was not able to add the cluster: Unable to connect to cluster. Error is: Unable to connect to any seed nodes, tried [u'172.31.30.71']

It's definitely been more than two minutes since the datacenter finished being created. Not sure if I should be adding credentials or if swapping `readlink` with `stat` somehow messed things up or if I'm doing something else wrong.

**Comment by cpoczatek** [comment]
Not sure why that's happening... Is this instance of OpsCenter still up? Can I have the url?

I think probably the datacenter didn't deploy. If there isn't a working cluster OpsCenter presents you with that dialog.

Once the datacenter CFn stack gives "CREATE_COMPLETE" you should be able to see the progress of the LCM install at the LCM URL ( something like http://opscenter-domain-name:8888/opscenter/lcm.html )

And if you go to the jobs page (something like http://opscenter-domain-name:8888/opscenter/lcm.html#/jobs ) it should show you the status of the last install job. Which brings up 2 questions:

- Is there a job at all?
- If there is, is the status *Failed*? You can click the "box with right arrow" to get job details, then again for node details, then a 3rd time for command details.

**Comment by cpoczatek** [comment]
Fairly certain this was related to #27. Should be fixed.
