### ISSUE TITLE
multi dc spark only detects itself as worker

### ISSUE THREAD

**Issue by RajatGoyal** [DSPN/amazon-cloudformation-dse#33]
I have installed 3 node cassandra cluster using multi-dc but spark master detects only itself as worker and does not detect other workers.

[![Screen Shot 2016-12-27 at 6.16.56 PM.png](https://s27.postimg.org/g1ihy7s0j/Screen_Shot_2016_12_27_at_6_16_56_PM.png)](https://postimg.org/image/z6lr7z6of/)

The workers are running on all the nodes, but master cannot detect other workers.

[![spark](https://s28.postimg.org/v7pim0mnh/Screen_Shot_2016_12_27_at_5_58_10_PM.png)](https://postimg.org/image/8j0bmg59l/)

**Comment by RajatGoyal** [comment]
Any updates on this?

**Comment by RajatGoyal** [comment]
So, I figured it out, spark intercommunication ports are not opened, mentioned here https://docs.datastax.com/en/datastax_enterprise/4.5/datastax_enterprise/sec/secConfFirePort.html

**Comment by cpoczatek** [comment]
All workload related ports should be open. Closing.
