### ISSUE TITLE
CassandraGroup CREATE_FAILED

### ISSUE THREAD

**Issue by MadDataScience** [DSPN/amazon-cloudformation-dse#35]
Trying out the new multidc deploy scripts. Not sure if I'm doing it right. I first run `deploy_opscenter.sh`. (I'm leaving the defaults alone for now.) I wait until I get the 	`CREATE_COMPLETE`. In fact, by the time I get to the next step, frequently a half hour or more has passed since that completes. Then I run `deploy_datacenter.sh` (again, leaving defaults alone). I get a few `CREATE_IN_PROGRESS` events and then it sits for a half-hour until I get a `UPDATE_IN_PROGRESS` event followed immediately by a `CREATE_FAILED` event followed by `ROLLBACK_IN_PROGRESS` and so on. This has happened to me twice now. Wondering if I'm doing something wrong or if something is busted (or a combination of the two). Please advise. Thank you.

**Comment by cpoczatek** [comment]
That was an error in the opscenter template (fwiw, a different path snuck in from the dev branch). This is fixed. Either stack should deploy in 5-10m, but note that at `CREATE_COMPLETE` for the datacenter stack the Opscenter instance is still installing/configuring DSE on all the DC nodes. The progress of this can be viewed by going to the `LCM_URL` (Opscenter stack output) and clicking on 'Jobs'

**Comment by cpoczatek** [comment]
Closed by commit d1fd7f2
