### ISSUE TITLE
multidc deployment fails because it's using private IPs

### ISSUE THREAD

**Issue by artooro** [DSPN/amazon-cloudformation-dse#38]
I just used the multidc deployment to do a new deployment in all 3 regions currently supported by the script.
The region where OpsCenter was deployed it also deployed the node just fine as well. But for the other 2 regions the initial OpsCenter job failed to connect to the nodes via SSH.

This is because they were set to the private IP addresses, as soon as I changed the IPs to the Elastic IPs and ran the `Install` job, it worked OK.

Or am I missing something and everyone else just has a VPN setup between their regions or something.

**Comment by cpoczatek** [comment]
No, you're not missing something. At the moment I'm not sure why this bug is happening. If you look at ~ line 280 in cfn-datacenter.json the metadata server is queried for the public ip and other values, and these are passed to the script that adds the node to the cluster. I'm not seeing an obvious typo, so I'm going to have to do a little debugging.

```
                  "cd install-datastax-ubuntu-master/bin/lcm \n",
                  "pubip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) \n",
                  "privip=$(curl http://169.254.169.254/latest/meta-data/local-ipv4) \n",
                  "nodeid=$(curl http://169.254.169.254/latest/meta-data/instance-id) \n",
                  "rack=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone) \n",
                  "./addNode.py ",
                  " --opsc-ip ", { "Ref" : "OpsCenterPubIP" },
                  " --clustername ", { "Ref" : "ClusterName" },
                  " --dcsize ", { "Ref" : "DataCenterSize" },
                  " --clustersize ", {"Ref" : "ClusterSize"},
                  " --dcname ", { "Ref" : "DataCenterName" },
                  " --rack $rack",
                  " --pubip $pubip",
                  " --privip $privip",
                  " --nodeid $nodeid",
                  " --dbpasswd ", { "Ref" : "DBPassword"}," \n"
```

**Comment by cpoczatek** [comment]
This was a error merging in changes from the dev branch, master is fixed now. Specially there was an incorrect url to pull in the datacenter template.

**Comment by artooro** [comment]
Great thanks! I'll re-do my deployment.
