### ISSUE TITLE
Add explicit spin up order/dependancies

### ISSUE THREAD

**Issue by cpoczatek** [DSPN/amazon-cloudformation-dse#5]
Right now, everything tries to come up at once. Should explicitly have it do:
- seed node
- other nodes
- OpsC

**Comment by benofben** [comment]
Despite what our doc says, you don't seem to need the seeds to come up before other nodes.  I have a jira open to that effect.

Similarly you should be able to spin OpsCenter up in parallel and rely on retry logic in manage existing cluster.

**Comment by cpoczatek** [comment]
It was more to be able to query the seed node hostname, and letting ec2 do its default dns thing.

Besides spin up time can you think of a reason _not_ to have it well ordered?
